<?php
$lebensmitt=array("Amaranth",
"Buchweizen",
"Dinkel",
"Gerste",
"Hafer",
"Hiobstränen",
"Hirse",
"Mais",
"Süßreis",
"Quinoa",
"Reis",
"Roggen",
"Sorghum",
"Weizen",
"Weizenkeime",
"Weizenkleie",
"Wildreis",
"Alfalfa",
"Artischocken",
"Auberginen",
"Avocados",
"Bambussprossen",
"Blumenkohl",
"Brennessel",
"Brokkoli",
"Brunnenkresse",
"Champignons",
"Chicoree",
"Chinakohl",
"Eisbergsalat",
"Endiviensalat",
"Feldsalat",
"Fenchel",
"Frühlingszwiebeln",
"Grüne Bohnen",
"Grünkohl",
"Gurken",
"Hokkaidokürbis",
"Hülsenfrüchtesprossen",
"Kapern",
"Kapuzinerkresse",
"Kartoffeln",
"Kochbananen",
"Kopfsalat",
"Kohl",
"Kohlrabi",
"Kopfsalat",
"Kürbis",
"Lauch",
"Löwenzahn",
"Mangold",
"Marone / Kastanien",
"Möhren",
"Mungbohnensprossen",
"Pakchoi",
"Paprika",
"Pastinaken",
"Portulak",
"Radicchio",
"Radieschen -und sprossen",
"Rettich, weiß",
"Rettich, schwarz",
"Rote Beete",
"Rotkohl",
"Rüben",
"Rucola, Rauke",
"Sauerampfer",
"Sauerkraut",
"Schalotten",
"Schwarzwurzel",
"Sellerie, Knolle und Stange",
"Shitakepilze",
"Sojasprossen",
"Spargel",
"Spinat",
"Steckrübe",
"Süßkartoffeln",
"Tomaten",
"Wasserkastanien",
"Weißkohl",
"Wirsingkohl",
"Wolkenohrpilze (schwarz)",
"Wolkenohrpilze (weiß)",
"Yamswurzeln",
"Zucchini",
"Zwiebeln, roh",
"Zwiebeln, gekocht und gebraten",
"Ananas",
"Äpfel",
"Apfelsinen",
"Aprikosen",
"Bananen",
"Birnen",
"Blaubeeren",
"Brombeeren",
"Datteln",
"Erdbeeren",
"Feigen",
"Granatapfel",
"Himbeeren",
"Holunderbeeren",
"Johannisbeeren",
"Kakis",
"Kirschen, süß",
"Kirschen, sauer",
"Kiwi",
"Kokosnuss",
"Limetten",
"Litschis",
"Mandarinen",
"Mango",
"Maulbeeren",
"Melone",
"Pampelmusen",
"Papaya",
"Pfirsiche",
"Pflaumen",
"Preiselbeere",
"Quitten",
"Rhabarber",
"Stachelbeeren",
"Weintrauben",
"Zitronen",
"Adzukibohnen",
"Bohnen, schwarz",
"Dicke Bohnen",
"Erbsen",
"Kichererbsen",
"Kidneybohnen",
"Limabohnen",
"Linsen",
"Mungbohnen",
"Sojabohnen, gelb",
"Sojabohnen, schwarz",
"Tofu",
"",
"NÜSSE UND SAMEN",
"Cashew",
"Erdnüsse",
"Esskastanien",
"Haselnüsse",
"Kokosmilch",
"Kokosnuß",
"Kürbiskerne",
"Mandeln",
"Pinienkerne",
"Pistazien",
"Sesam (schwarz und weiß)",
"Sonnenblumenkerne",
"Walnüsse",
"Anis",
"Basilikum, frisch",
"Basilikum, getrocknet",
"Beifuß",
"Bockshornkleesamen",
"Bohnenkraut, frisch",
"Bohnenkraut, getrocknet",
"Brennessel",
"Cayennenpfeffer",
"Chilli",
"Dill, frisch und getrocknet",
"Estragon, frisch",
"Estragon, getrocknet",
"Fenchelkörner",
"Ingwer, frisch",
"Ingwer, getrocknet",
"Kakao",
"Kardamon",
"Karob",
"Knoblauch",
"Koriandergrün, frisch und Samen",
"Kreuzkümmel / Cumin",
"Kümmel",
"Kurkuma",
"Liebstöckel",
"Lorbeerblätter",
"Majoran, frisch und getrocknet",
"Meerrettich",
"Minze",
"Mohn",
"Mu-Erh-Pilz",
"Muskatnuß",
"Nelken",
"Oregano, getrocknet",
"Oregano, frisch",
"Paprika",
"Petersilie",
"Pfeffer",
"Piment",
"Reissirup",
"Rosmarin, frisch",
"Rosmarin, getrocknet",
"Safran",
"Salbei, frsich",
"Salbei, getrocknet",
"Salz",
"Schnittlauch, frisch und getrocknet",
"Senf",
"Stangenzimt",
"Sternanis",
"Süßholz",
"Tamarinde",
"Thymian, frisch",
"Thymian, getrocknet",
"Vanille",
"Wacholder",
"Zimtrinde",
"Erdnußöl",
"Essig",
"Honig",
"Kürbiskernöl",
"Leinöl",
"Malz",
"Melasse",
"Olivenöl",
"Rapsöl",
"Sesamöl",
"Sirup",
"Sojaöl",
"Sonnenblumenöl",
"Vollrohrzucker",
"Weizenkeimöl",
"Zucker, weiß",
"Apfelsaft",
"Alkohohl, hochprozentig",
"Altbier",
"Banchatee",
"Bier, Pils",
"Birnensaft",
"Bitterlikör",
"Champagner",
"Chrysanthemen",
"Cognac",
"Fencheltee",
"Getreidekaffee",
"Glühwein",
"Hagebutten",
"Hibiskustee",
"Himbeerblätter",
"Holunderblüten",
"Honigwein",
"Jasmin",
"Kaffee",
"Kakao",
"Kamille",
"Likör",
"Lindenblüten",
"Pu-Erh-Tee",
"Pfefferminze",
"Portwein",
"Prosecco",
"Maishaartee",
"Malventee",
"Mineralwasser",
"Orangenblüttentee",
"Reiswein (Sake)",
"Sekt",
"Sojamilch",
"Süßholz",
"Tee, schwarzer",
"Tee, grüner",
"Tee, weiß",
"Traubensaft rot / weiß",
"Tuo-Cha-Tee",
"Wein, weiß",
"Wein, rot",
"Weizenbier",
"Weißdorn",
"Yogi-Tee",
"Zitronenmelisse",
"Butter",
"Enteneier",
"Eier, Huhn",
"Harzer Käse",
"Joghurt",
"Kuhmilch",
"Parmesankäse",
"Münsterkäse",
"Schafsmilch- und Käse",
"Schimmelkäse",
"Ziegenmilch- und Käse",
"Sahne, süß",
"",
"FISCH UND MEERESTIERE",
"Aal",
"Abalone",
"Auster",
"Barsch",
"Forelle",
"Garnele (Shrimps, Crevette)",
"Geräucherter Fisch",
"Heilbutt",
"Hering",
"Hummer",
"Kabeljau",
"Karpfen",
"Kaviar",
"Krabbe",
"Krebs",
"Lachs",
"Languste",
"Makrele",
"Miesmuschel",
"Sardelle",
"Scholle",
"Tintenfisch",
"Thunfisch",
"FLEISCH",
"Ente",
"Gans",
"Gegrilltes Fleisch",
"Geräuchertes Fleisch",
"Gepökeltes Fleisch",
"Gesalzenes Fleisch",
"Luftgetrocknetes Fleisch",
"Hammel",
"Hirsch",
"Huhn",
"Kaninchen",
"Lamm",
"Pute",
"Rind",
"Salami",
"Schaf",
"Schinken",
"Schwein",
"Wildfleisch (Reh, Hase, Schwein)",
"Ziege",
"Algen",
"Agar-Agar",
"Blütenpollen und Gelee Royal",
"Hefe",
"Korinthe",
"Kuzu",
"Oliven",
"Miso",
"Pfeilwurzelmehl",
"Rosine",
"Salz",
"Sojasoße und Tamari",
"Sultanine",
"Umeboshi-Pflaume",
"test"
);


?>